### ISSUE TITLE
Unable to obtain the desired pretrained weight

### ISSUE THREAD

**Issue by seunghan96** [wengwenchao123/DDGCRN#3]
Hi :)
When running the code according to the author's instructions, the results from the table are not reproducible. 
I would like to inquire if there is an issue with the code that might be causing this inconsistency.

**Comment by wengwenchao123** [comment]
Hello, may I ask which dataset you are referring to when you say that the results cannot be reproduced? If it's dataset "03," please set the "mape_thresh" parameter to 0.01 in the relevant config_file.

This error occurs because when normalizing and denormalizing the predicted data, originally zero values can become very small values due to errors, which in turn leads to abnormal calculation of MAPE.

So, setting MAPE=0.01 can filter out these abnormal values. In fact, I had previously tried to fix the code bug by not normalizing the actual values of the predictions, and the results showed that it could avoid encountering this issue.

I will find time later to upload the bug-fixed code.

**Comment by seunghan96** [comment]
Apologies for the delayed response! I was able to resolve this issue with your assistance :)"
